{ config, pkgs, ... }: 

{
	# Import other configuration modules
	# (hardware-configuration.nix is autogenerated upon installation)
	# paths in nix expressions are always relative the file which defines them
	imports = [ 
		../../../hardware-configuration.nix
		../../private/users.nix
	];
				
	# Boot Loader
	boot.loader.systemd-boot.enable = true;
	boot.loader.efi.canTouchEfiVariables = true;
	
	# ZFS File System
	boot.supportedFilesystems = [ "zfs" ];
	boot.zfs = {
		extraPools = [ "vpool" ];
		forceImportRoot = false;
		forceImportAll = false;
	};
	services.zfs.autoScrub.enable = true;
		
	# Localization
	time.timeZone = "US/Denver";
	i18n = {
		consoleFont = "roboto-mono";
		consoleKeyMap = "us";
		defaultLocale = "en_US.UTF-8";
	};

	# Host Name
	networking.hostName = "portland";

	# Networking
	networking.networkmanager.enable = true;
	
	# Packages
	environment.systemPackages = with pkgs; [
		git
		ranger
		tmux
		unzip
		vim
		wget
	];
	
	# Fonts
	fonts = {
		enableFontDir = true;
		fontconfig {
			enable = true;
			defaultFonts.monospace = [ "roboto-mono" ];
			defaultFonts.sansSerif = [ "roboto" ];
			defaultFonts.serif = [ "roboto-slab" ];
		};
		fonts = with pkgs; [
			roboto
			roboto-mono
			roboto-slab
		];
	};
						
	# Some programs need SUID wrappers, can be configured further or are
	# started in user sessions.
	programs.bash.enableCompletion = true;
	programs.mtr.enable = true;
	programs.gnupg.agent = { enable = true; enableSSHSupport = true; };

	# OpenSSH Service
  services.openssh = {
    enable = true;
    ports = 8668;
    permitRootLogin = "no";
    passwordAuthentication = false;
    extraConfig = "
      # Allow Local Lan to login with password authentication
      Match address 192.168.8.0/24
        PasswordAuthentication yes
    ";
  };

	# Fail2ban Service
  services.fail2ban = {
    enable = true;
    jails.DEFAULT = ''bantime = 3600'';
    jails.sshd = ''
      filter = sshd
      maxretry = 4
      action = iptables[name=ssh, port=8668, protocol=tcp]
      enabled = true
    '';
    jails.sshd-dos = ''
      filter = sshd-ddos
      maxretry = 2
      action = iptables[name=ssh, port=8668, protocol=tcp]
      enabled = true
    '';
    jails.port-scan = ''
      filter = port-scan
      action = iptables-allports[name=port-scan]
      maxretry = 2
      bantime = 7200
      enabled = true
    '';
  };

  environment.etc."fail2ban/filter.d/port-scan.conf".text = ''
    [Definition]
    failregex = rejected connection: .* SRC=<HOST>
  '';

	# Docker Service
	virtualisation.docker = {
		enable = true;
		enableOnBoot = true;
		extraOptions = "-g /vpool/docker";
	};

	# Firewall
	networking.firewall.enable = true;
	networking.firewall.allowedTCPPorts = [ 8668 ];
	#networking.firewall.allowedUDPPorts = [ ...];
    
	# This value determines the NixOS release with which your system is to be
	# compatible, in order to avoid breaking some software such as database
	# servers. You should change this only after NixOs release notes say you
	# should.
	system.stateVersion = "18.03"; # Did you read the comment?
}
